package logic;

public enum OperationType {
    SAVE_OR_UPDATE,
    GET_USERS,
    CHECK_USER,
    CLIENT_INFO,
    USED_SERVICES,
    CLIENT_RAITING,
    CREATED_RESERVATIONS,
    RECEPT_CREATED_RESERVATIONS,
    ROOM_RAITING,
    GET_RECEPTIONIST,
    LOGIN,
    GET_ROOMS,
    GET_ADS,
    GET_CLIENTS,
    GET_CUS,
    GET_HOTEL,
    GET_RESERVATIONS,
    GET_SERVICE_CATEGORY,
    DELETE,
    GET_USER_NOW,
    AAD_TO_USERS
}
