-- Generated by Oracle SQL Developer Data Modeler 20.2.0.167.1538
--   at:        2020-10-26 14:41:50 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE addit_serv (
    addit_serv_id     INTEGER NOT NULL,
    addit_serv_title  VARCHAR2(200),
    addit_serv_price  NUMBER
);

ALTER TABLE addit_serv ADD CONSTRAINT addit_serv_pk PRIMARY KEY ( addit_serv_id );

CREATE TABLE client_addit_serv (
    client_id      INTEGER NOT NULL,
    addit_serv_id  INTEGER NOT NULL
);

CREATE TABLE clients (
    client_id               INTEGER NOT NULL,
    client_name             VARCHAR2(255),
    client_birth_date       DATE,
    country_id              INTEGER NOT NULL,
    client_sex              INTEGER,
    client_passport_number  VARCHAR2(50),
    client_passport_date    DATE,
    client_car_number       VARCHAR2(50),
    client_note             VARCHAR2(255),
    client_rating           INTEGER
);

ALTER TABLE clients ADD CONSTRAINT clients_pk PRIMARY KEY ( client_id );

CREATE TABLE countyis (
    county_id     INTEGER NOT NULL,
    country_name  VARCHAR2(100)
);

ALTER TABLE countyis ADD CONSTRAINT countyis_pk PRIMARY KEY ( county_id );

CREATE TABLE food_type (
    food_type_id  INTEGER NOT NULL,
    food_type     VARCHAR2(50)
);

ALTER TABLE food_type ADD CONSTRAINT food_type_pk PRIMARY KEY ( food_type_id );

CREATE TABLE reservation (
    reservation_id         INTEGER NOT NULL,
    reservation_type       INTEGER NOT NULL,
    room_type              INTEGER NOT NULL,
    cancel_type            INTEGER NOT NULL,
    vucher                 INTEGER,
    start_date             DATE,
    end_date               DATE,
    adults                 INTEGER,
    food_type_id           INTEGER NOT NULL,
    room_id                INTEGER NOT NULL,
    total_price            NUMBER,
    reservation_status_id  INTEGER NOT NULL,
    notes                  VARCHAR2(255),
    receptionist_id        INTEGER
);

ALTER TABLE reservation ADD CONSTRAINT reservation_pk PRIMARY KEY ( reservation_id );

CREATE TABLE reservation_cancel_types (
    reservation_cancel_type_id  INTEGER NOT NULL,
    reservation_cancel_type     VARCHAR2(50)
);

ALTER TABLE reservation_cancel_types ADD CONSTRAINT reservation_cancel_type_pk PRIMARY KEY ( reservation_cancel_type_id );

CREATE TABLE reservation_clients (
    reservation_id  INTEGER NOT NULL,
    client_id       INTEGER NOT NULL
);

CREATE TABLE reservation_status (
    reservation_status_id  INTEGER NOT NULL,
    reservation_status     VARCHAR2(50)
);

ALTER TABLE reservation_status ADD CONSTRAINT reservation_status_pk PRIMARY KEY ( reservation_status_id );

CREATE TABLE reservation_types (
    reservation_type_id  INTEGER NOT NULL,
    reservation_type     VARCHAR2(50)
);

ALTER TABLE reservation_types ADD CONSTRAINT reservation_types_pk PRIMARY KEY ( reservation_type_id );

CREATE TABLE room_types (
    type_id    INTEGER NOT NULL,
    type_name  VARCHAR2(50)
);

ALTER TABLE room_types ADD CONSTRAINT room_types_pk PRIMARY KEY ( type_id );

CREATE TABLE rooms (
    room_id      INTEGER NOT NULL,
    type_id      INTEGER NOT NULL,
    room_number  VARCHAR2(10),
    room_rating  INTEGER
);

ALTER TABLE rooms ADD CONSTRAINT rooms_pk PRIMARY KEY ( room_id );

CREATE TABLE user_roles (
    user_role_id  INTEGER NOT NULL,
    user_role     VARCHAR2(50)
);

ALTER TABLE user_roles ADD CONSTRAINT user_roles_pk PRIMARY KEY ( user_role_id );

CREATE TABLE users (
    user_id        INTEGER NOT NULL,
    user_name      VARCHAR2(50),
    user_password  VARCHAR2(50),
    role_id        INTEGER NOT NULL
);

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( user_id );

ALTER TABLE client_addit_serv
    ADD CONSTRAINT client_addit_serv_as_fk FOREIGN KEY ( addit_serv_id )
        REFERENCES addit_serv ( addit_serv_id );

ALTER TABLE client_addit_serv
    ADD CONSTRAINT client_addit_serv_c_fk FOREIGN KEY ( client_id )
        REFERENCES clients ( client_id );

ALTER TABLE clients
    ADD CONSTRAINT clients_countyis_fk FOREIGN KEY ( country_id )
        REFERENCES countyis ( county_id );

ALTER TABLE reservation
    ADD CONSTRAINT reservation_cancel_types_fk FOREIGN KEY ( cancel_type )
        REFERENCES reservation_cancel_types ( reservation_cancel_type_id );

ALTER TABLE reservation_clients
    ADD CONSTRAINT reservation_clients_clients_fk FOREIGN KEY ( client_id )
        REFERENCES clients ( client_id );

ALTER TABLE reservation_clients
    ADD CONSTRAINT reservation_clients_fk FOREIGN KEY ( reservation_id )
        REFERENCES reservation ( reservation_id );

ALTER TABLE reservation
    ADD CONSTRAINT reservation_food_type_fk FOREIGN KEY ( food_type_id )
        REFERENCES food_type ( food_type_id );

ALTER TABLE reservation
    ADD CONSTRAINT reservation_room_types_fk FOREIGN KEY ( room_type )
        REFERENCES room_types ( type_id );

ALTER TABLE reservation
    ADD CONSTRAINT reservation_rooms_fk FOREIGN KEY ( room_id )
        REFERENCES rooms ( room_id );

ALTER TABLE reservation
    ADD CONSTRAINT reservation_status_fk FOREIGN KEY ( reservation_status_id )
        REFERENCES reservation_status ( reservation_status_id );

ALTER TABLE reservation
    ADD CONSTRAINT reservation_types_fk FOREIGN KEY ( reservation_type )
        REFERENCES reservation_types ( reservation_type_id );

ALTER TABLE rooms
    ADD CONSTRAINT rooms_room_types_fk FOREIGN KEY ( type_id )
        REFERENCES room_types ( type_id );

ALTER TABLE users
    ADD CONSTRAINT users_user_roles_fk FOREIGN KEY ( role_id )
        REFERENCES user_roles ( user_role_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             0
-- ALTER TABLE                             25
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
